version: '3'

services:
    backend:
        build:
            context: docker/php
        volumes:
            - .:/app
        env_file:
            - .env
        ports:
            - "8088:8088"
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
            POSTGRES_USER: test
        ports:
            - "5433:5432"